# Data configuration
data:
  kaggle_data_dir: "data/kaggle_math"
  train_dir: "data/train"
  val_dir: "data/val" 
  test_dir: "data/test"
  num_classes: 45  # Updated to match symbol mapper vocabulary size
  input_size: 128  # Image input size

# Model configuration
model:
  name: "SimpleMathOCR"
  input_channels: 1
  hidden_dim: 256
  encoder_layers: 3
  use_decoder: true  # Use external decoder architecture

# Decoder configuration
decoder_type: "rnn"  # Options: "rnn", "transformer"
max_length: 50
num_layers: 2

# Training configuration
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
  device: "cpu"
  save_every: 5

# Logging configuration
logging:
  level: "INFO"
  log_dir: "logs"
  tensorboard_dir: "runs"

# Paths configuration
paths:
  model_save_dir: "models"
  output_dir: "outputs"

# Symbol mapping (comprehensive LaTeX symbols)
symbols:
  vocab:
    0: "+"
    1: "-"
    2: "="
    3: "\\times"
    4: "\\div"
    5: "\\frac"
    6: "\\sqrt"
    7: "\\alpha"
    8: "\\beta"
    9: "\\pi"
    10: "\\int"
    11: "\\sum"
    12: "\\infty"
    13: "\\leq"
    14: "\\geq"
    15: "\\cdot"
    16: "\\sin"
    17: "\\cos"
    18: "\\tan"
    19: "\\log"
    20: "("
    21: ")"
    22: "["
    23: "]"
    24: "{"
    25: "}"
    26: "x"
    27: "y"
    28: "z"
    29: "n"
    30: "0"
    31: "1"
    32: "2"
    33: "3"
    34: "4"
    35: "5"
    36: "6"
    37: "7"
    38: "8"
    39: "9"
    40: " "
    41: "<PAD>"
    42: "<START>"
    43: "<END>"
    44: "<UNK>"